
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etcmyqkdgeohchzwswsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0Y215cWtkZ2VvaGNoendzd3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMjMwMTUsImV4cCI6MjA2MDc5OTAxNX0.Kc5aodedJc9N4ab5cOsQnsbiOOfUEZtXoylH3Aii_Ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
